---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: getkimball-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "kimball-api.serviceAccountName" . }}
  namespace: getkimball-{{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: getkimball-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
