---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: getkimball
rules:
- apiGroups:
  - apps
  - ''
  resources:
  - 'configmaps'
  resourceNames:
  - "features-state-store"
  - "getkimball-features"
  verbs:
  - get
  - list
  - status
  - update
- apiGroups:
  - apps
  - ''
  resources:
  - 'configmaps'
  verbs:
  # Create can't be restricted by resource name
  - create
