---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: getkimball
rules:
- apiGroups:
  - apps
  - ''
  resources:
  - 'configmaps'
  verbs:
  - get
  - list
  - status
  - update
