apiVersion: apps/v1
kind: Deployment
metadata:
  name: features
  namespace: getkimball
  labels:
    app: features
spec:
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: features
  template:
    metadata:
      namespace: getkimball
      labels:
        app: features
    spec:
      serviceAccountName: getkimball
      containers:

      - name: features
        image: 422221479733.dkr.ecr.us-east-1.amazonaws.com/features:master-2e54aa93098c31f63a6aa49cadd3bdf38e828fc3
        ports:
        - name: api
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /alive
            port: api
        env:
        - name: "SENTRY_DSN"
          valueFrom:
            secretKeyRef:
              name: features
              key: sentry_dsn
        - name: "ADDITIONAL_NAMESPACES"
          value: "default"
