# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: features
  build: pr
namespace: getkimball

resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment-api.yaml
- deployment-sidecar.yaml
- namespace.yaml
- service-account.yaml
- service.yaml
- service-sidecar.yaml
