# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: features
  build: pr
namespace: getkimball

resources:
- deployment.yaml
- namespace.yaml
- service.yaml
