# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: service-controller

resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- namespace.yaml
- service-account.yaml
