---
apiVersion: v1
kind: Service
metadata:
  name: features-sidecar
  namespace: getkimball
spec:
  selector:
    app: features-sidecar
  ports:
    - protocol: TCP
      port: 80
      targetPort: api
      name: http
