namePrefix: production-
commonLabels:
  org: getkimball
  variant: production
commonAnnotations:
  note: Hello, I am production!
patchesStrategicMerge:
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
