# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import features_proto_pb2 as features__proto__pb2


class KimballIntegrationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EventStream = channel.stream_unary(
                '/KimballIntegration/EventStream',
                request_serializer=features__proto__pb2.KimballEvent.SerializeToString,
                response_deserializer=features__proto__pb2.Response.FromString,
                )


class KimballIntegrationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EventStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KimballIntegrationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EventStream': grpc.stream_unary_rpc_method_handler(
                    servicer.EventStream,
                    request_deserializer=features__proto__pb2.KimballEvent.FromString,
                    response_serializer=features__proto__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KimballIntegration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KimballIntegration(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EventStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/KimballIntegration/EventStream',
            features__proto__pb2.KimballEvent.SerializeToString,
            features__proto__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
