name: Build and plan

on: [pull_request]

jobs:

  build_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: |
        TAG=philipcristiano/hellerl_world:$(date +%s)
        docker build . --file Dockerfile --tag $TAG
        docker push $TAG
        printf "docker_image = \"%s\"\n\n" $TAG > docker_image.tfvars
      env:
        ORG: philipcristiano
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload docker image tag
      uses: actions/upload-artifact@v1
      with:
        name: build_docker
        path: docker_image.tfvars

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    needs: build_docker

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Download docker_build artifact
        uses: actions/download-artifact@v1
        with:
          name: build_docker
      - name: Copy docker image to tfvars file
        run: |
          cp build_docker/docker_image.tfvars docker_image.auto.tfvars
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
          tf_actions_cli_credentials_hostname: app.terraform.io
          tf_actions_cli_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: '.'
